### DISCUSSION TITLE
Generate client stub for external dependency

### DISCUSSION THREAD

**Discussion by haf** [timostamm/protobuf-ts#589] [Q&A] [answered]
I want to generate a client for `opentelemetry/proto/collector/trace/v1/trace_service.proto` from here https://buf.build/opentelemetry/opentelemetry/docs/main:opentelemetry.proto.collector.trace.v1#opentelemetry.proto.collector.trace.v1.TraceService

I have buf.yaml:

```yaml
version: v1

deps:
- buf.build/opentelemetry/opentelemetry

breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

and `buf.gen.yaml`:

```yaml
version: v1

managed:
  enabled: true

plugins:
- plugin: buf.build/community/timostamm-protobuf-ts:v2.9.1
  out: lib/grpc
  opt:
  - client_generic
  - optimize_speed
  - server_none
```

but when running `buf generate`, I only get these folders:

```
❯ ls lib/grpc/
google       node_modules
```

I understand that I'm not specifically referencing the service, but I also can't find **how** I specifically reference the service that I want to generate a client for. How do I generate a client for this file?
