### ISSUE TITLE
Buf generated duplicate file with protoc-gen-ts

### ISSUE THREAD

**Issue by sorcererxw** [timostamm/protobuf-ts#165]
```
# buf.yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
```
```
# buf.gen.yaml
version: v1

plugins:
  - name: ts
    out: ./proto
    opt:
      - generate_dependencies
      - long_type_string
      - client_generic
      - server_none
    path: ../node/node_modules/.bin/protoc-gen-ts
```

The output of `buf generate`:
```
Warning: Duplicate generated file name "google/protobuf/descriptor.ts". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.
Warning: Duplicate generated file name "google/api/http.ts". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.
```

protoc-gen-ts may need to ignore files that have already been generated.
