### ISSUE TITLE
Publishing Remote Plugin on BSR

### ISSUE THREAD

**Issue by MHDante** [timostamm/protobuf-ts#249]
Hi @timostamm. 
Thank you again for a wonderful library. 

I'm sure you've heard, but Buf has just released a Remote compilation platform: https://buf.build/blog/remote-plugin-execution

Given the support for buf show in #93, are there any plans for adding BSR plugin publishing to this repo's build process?

**Comment by timostamm** [comment]
Hey Dante, 

thanks for suggestions. protobuf-ts is already available: https://buf.build/timostamm/plugins/protobuf-ts
I've added a link in the top-level README so it's a bit easier to discover.

An example code generation template:

```yaml
# buf.gen.yaml
version: v1
plugins:
  - remote: buf.build/timostamm/plugins/protobuf-ts:v2.2.2-0
    out: gen/
    opt:
      - long_type_string
      - generate_dependencies
```
