### ISSUE TITLE
Web stubs not generated if option `client_grpc1` is set

### ISSUE THREAD

**Issue by Janaka-Steph** [timostamm/protobuf-ts#302]
I would like to generate both web and nodeJS stubs.

This is my config
```
version: v1
plugins:
  - remote: buf.build/timostamm/plugins/protobuf-ts
    out: src/api-spec/protobuf/gen/js
    opt:
      - client_grpc1
      - add_pb_suffix
      - eslint_disable
      - ts_nocheck
```

Is it a bug or am I missing something?
