### ISSUE TITLE
Sending `bytes` in a message and the data will contain unexpected header and footer

### ISSUE THREAD

**Issue by FlysoftBeta** [timostamm/protobuf-ts#497]
Hi, I am sending some bytes data from the Python backend using grpc.
For example, if I send the message in this way:
![image](https://user-images.githubusercontent.com/49718840/223725274-f6ee178a-d757-4b12-8cd6-ac4b9dd964ab.png)
and call it from the client side:
![image](https://user-images.githubusercontent.com/49718840/223725535-bb2411ae-5d06-4d5d-bb3e-692b02ce8de2.png)
The message will contain unexpected header and footer:
![图片](https://user-images.githubusercontent.com/49718840/223726054-e2a8dc88-ffbe-483f-a416-0305288d0fa5.png)

**Comment by FlysoftBeta** [comment]
> Your server is serving gRCP, but your client is expecting gRCP-**web**. It's a different protocol. If your client runs in the browser, you have to a proxy between that can translate, like envoy.

Thanks for reply. I have set up envoy proxy already. This is what my envoy configuration file looks like:
```yaml
admin:
    access_log_path: /tmp/admin_access.log
    address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
    listeners:
        - name: listener_0
          address:
              socket_address: { address: 0.0.0.0, port_value: 8080 }
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          codec_type: auto
                          stat_prefix: ingress_http
                          route_config:
                              name: local_route
                              virtual_hosts:
                                  - name: local_service
                                    domains: ["*"]
                                    routes:
                                        - match: { prefix: "/" }
                                          route:
                                              cluster: echo_service
                                              timeout: 0s
                                              max_stream_duration:
                                                  grpc_timeout_header_max: 0s
                                    cors:
                                        allow_origin_string_match:
                                            - prefix: "*"
                                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                                        max_age: "1728000"
                                        expose_headers: custom-header-1,grpc-status,grpc-message
                          http_filters:
                              - name: envoy.filters.http.grpc_web
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                              - name: envoy.filters.http.cors
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                              - name: envoy.filters.http.router
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    clusters:
        - name: echo_service
          connect_timeout: 0.25s
          type: logical_dns
          http2_protocol_options: {}
          lb_policy: round_robin
          load_assignment:
              cluster_name: cluster_0
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 127.0.0.1
                                      port_value: 4000

```
