### ISSUE TITLE
unused parameters in the empty.ts are causing TypeScript check errors

### ISSUE THREAD

**Issue by tidycode** [timostamm/protobuf-ts#608]
This empty.ts was auto generated from protobuf file "google/protobuf/empty.proto" (package "google.protobuf", syntax proto3)

the error is in the function internalBinaryRead
![image](https://github.com/timostamm/protobuf-ts/assets/5961374/1900ef19-a64c-4939-b4c9-7b28120b4f36)

```
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Empty): Empty {
        return target ?? this.create();
    }
```
if run script `vue-tsc --noEmit --skipLibCheck`
It will cause ts-check error
'reader' is declared but its value is never read.
'length' is declared but its value is never read.
'options' is declared but its value is never read.

**Comment by danielvandenberg95** [comment]
It's not only in empty.ts. It's in any proto message without members. A solution would be to prefix unused variables with _.

Use-case: I've got multiple empty types because I expect to add members in the future.

**Comment by danielvandenberg95** [comment]
https://github.com/timostamm/protobuf-ts/pull/609

**Comment by danielvandenberg95** [comment]
As timostamm suggested there, generate proto with  --ts_opt ts_nocheck.

**Comment by timostamm** [comment]
See the documentation [here](https://buf.build/docs/generate/tutorial#2.-configure-your-buf.gen.yaml-file).

```yaml
version: v1
plugins:
  - plugin: buf.build/community/timostamm-protobuf-ts:v2.9.1
    out: ./ts
    opt: ts_nocheck
```

For multiple plugin options, use:
```yaml
version: v1
plugins:
  - plugin: ...
    out: ...
    opt: 
      - ts_nocheck
      - other_option
```
