### ISSUE TITLE
ServiceInfo doesn't exist in target module `@protobuf-ts/runtime-rpc`

### ISSUE THREAD

**Issue by zeddo123** [timostamm/protobuf-ts#697]
Hi,

I'm trying to fetch data from a grpc server with `nextjs` (server-side) and the generated SDK code from buf.build's BSR. But I'm getting this error:
```ts
Export ServiceInfo doesn't exist in target module
   5 | // @ts-nocheck
   6 | import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
>  7 | import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
```

I've checked the version numbers of the generated code and the installed modules and they seem to match:
```ts
//service_pb.client.d.ts

// @generated by protobuf-ts 2.9.6 with parameter output_javascript,optimize_code_size,long_type_string,add_pb_suffix,ts_nocheck,eslint_disable
```

```yaml
//pnpm-lock.yaml

'@protobuf-ts/runtime-rpc':
        specifier: ^2.9.6
        version: 2.9.6
```
