### ISSUE TITLE
Can this be used with buf?

### ISSUE THREAD

**Issue by atreya2011** [timostamm/protobuf-ts#93]
Thank you for making this great tool for generating idiomatic TypeScript code from proto files along with RPC support as well!
I was wondering how to use this with [buf](https://buf.build). Any advice would be helpful. Thanks in advance 🙇🏼

**Comment by timostamm** [comment]
Yes, protobuf-ts is a regular protoc plugin and can be used with buf.

Example `buf.gen.yaml`:

```yaml
version: v1beta1

# The plugins to run.
plugins:

    # The name of the plugin.
    # Required.
    # By default, buf generate will look for a binary named protoc-gen-NAME on your $PATH.
  - name: ts

    # The the relative output directory.
    # Required.
    out: gen/ts

    # See "available plugin parameters"
    # https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#the-protoc-plugin
    opt: generate_dependencies,long_type_string

    # The custom path to the plugin binary, if not protoc-gen-NAME on your $PATH.
    # Assuming you have installed @protobuf-ts/plugin in the working directory:
    path: ./node_modules/@protobuf-ts/plugin/bin/protoc-gen-ts
```

See https://docs.buf.build/generate-usage

If you encounter any problems, let me know.
